CREATE TYPE RESULT AS ENUM ('WIN', 'LOSS', 'DRAW', 'NOT_PLAYED');

CREATE TABLE "OntarioOpenPlayer" (
    "CFCId" INT PRIMARY KEY,
    "rating" INT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "age" INT NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "isFemale" BOOLEAN DEFAULT FALSE,
    "isPlayingUp" BOOLEAN DEFAULT FALSE,
    "hasPaid" BOOLEAN DEFAULT FALSE,
    "result1" RESULT DEFAULT 'NOT_PLAYED',
    "result2" RESULT DEFAULT 'NOT_PLAYED',
    "result3" RESULT DEFAULT 'NOT_PLAYED',
    "result4" RESULT DEFAULT 'NOT_PLAYED',
    "result5" RESULT DEFAULT 'NOT_PLAYED',
    "result6" RESULT DEFAULT 'NOT_PLAYED'
);
